### ISSUE TITLE
Configurar o docker composer 

### ISSUE THREAD

**Issue by HenriqueMundim** [Laranja-Mecanica/orange-portifolio-api#15]

**Comment by eoSalinas** [comment]
Sugestão de imagem e config para o PostgreSql no docker composer

`docker-compose.yml`:

``` yml
version: '3'

services:
  orange-portifolio-pg:
    image: 'bitnami/postgresql'
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=orange-portifolio-api
```
